const bookMenu = [
  {
    item: "Upanishads",
    description: "Philosopical texts exploring the spiritual essence of the universe and the self; part of the vedic literature.",
    image: "https://www.prabhatbooks.com/upload/1690102963.jpg",
    price: 999,
    author:"Ancient Indian Sages(rishis)",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Ramcharitmanas",
    description: "Ramcharitmanas is a devotional epic by Tulsidas that narrates the life and virtues of Lord Rama in simple Awadhi language",
    image: "https://i.etsystatic.com/45521486/r/il/647243/5177188420/il_1588xN.5177188420_f483.jpg",
    price: 678,
    author:"Goswami Tulsidas",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Hanuman Chalisa",
    description: "Hanuman Chalisa is a devotional hymn of 40 verses composed by the saint Tulsidas in praisa of Lord Hanuman, celebrating his strength, devotion, wisdom and wnwavering service to Lord rama; It is widely recited for protection, courage, and spiritual upliftment.",
    image: "https://m.media-amazon.com/images/I/71j9kEJ1Y7L._SL1500_.jpg",
    price: 899,
    author:"Goswami Tulsidas",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "The Rig Veda",
    description: "The rig veda is the oldest sacred text of Hinduism, comprising hymns that explore cosmic creation, divine forces, and spiritual wisdom.",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/book/k/i/k/rigveda-book-hindi-original-imah3nthh9mzmezv.jpeg?q=70&crop=false",
    price: 380,
    author:"Many anciant sages(rishis)",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Skanda Purana",
    description: "The largest of the puranas, primarily devoted to Lord Kartikeya(Skanda) and various pilgrimage sites.",
    image: "https://www.bhaktiwallpapers.com/uploads/2024/02/shree-murugan-god-vedic-god-murugan-subrahmanya-murugan-murugan-palaniappa-4k-hd-phone-wallpaper-tz0e-1708780484.jpg",
    price: 580,
    author:"VedaVyasa",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Shiv Puran",
    description: "The Shiv Puran is a sacred text that narrates the glory, stories and teachings of Lord Shiva, emphasizing devoties(bhakti), cosmic creation, and spiritual liberation.",
    image: "https://5.imimg.com/data5/SELLER/Default/2024/1/379326526/YX/GO/OH/3726307/shiv-puran-1000x1000.jpg",
    price: 390,
    author:"VedaVyasa",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Ramayan",
    description: "Ramayana is the ancient Sanskrit epic written by Valmiki, which tells the story of Lord Rama, his exile, battles with Ravana, and his return to Ayodhya. It is considered one of the two major epics of Hindu literature, along with the Mahabharata.",
    image: "https://pbs.twimg.com/media/FIYXYx6VEAI7rD-.jpg",
    price: 799,
    author:"Maharishi Valmiki",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Bhagavad Gita ",
    description: "A dialogue between Krishna and Arjuna on duty, life, and spirituality—central to Hindu philosophy.",
    image: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781647226787/bhagavad-gita-9781647226787_hr.jpg",
    price: 1100,
    author:"VedaVyasa",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Yoga Sutras of Patanjali",
    description: "Yoga Sutras of Patanjali is a foundational guide to the philosophy and  practice of yoga, outlining the path to spiritual liberation through mental discipline and self-realization.",
    image: "https://m.media-amazon.com/images/I/71PHWeldXPL._SL1500_.jpg",
    price: 899,
    author:"Sage Patanjali",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "Mahabharat",
    description: "**Mahabharat** is an ancient epic that narrates the great war between the Pandavas and Kauravas, highlighting themes of duty, justice, and dharma.",
    image: "https://assetscdn1.paytm.com/images/catalog/product/9/97/9789386382009_1011988/1602231950838_0..jpg",
    price: 1299,
    author:"VedaVyasa",
    owner:"6805cfd735ab1d080a4927fd",
  },
  {
    item: "The Yajur veda",
    description: "Focuses on ritualistic formulas and ceremonies.",
    image: "https://rukminim2.flixcart.com/image/832/832/xif0q/regionalbooks/n/n/w/yajur-veda-book-in-medium-size-original-imagtbqyczhwdz4j.jpeg?q=70&crop=false",
    price: 366,
    author:"Many anciant sages(rishis)",
    owner:"6805cfd735ab1d080a4927fd",
  }
];

module.exports = {data : bookMenu};